name: Checkout

on: 
    [ push ]

jobs:
    build: 
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          checkout: [funktioniert1, funktioniert2]
      
      runs-on: ${{ matrix.os }}
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4
