name: Checkout

on: 
    [ push ]

jobs:
    build: 
    
      
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Build and Test
          run: |
            npm install
            npm test
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
        - name: Build image
          run: docker image build -t raupechr/cicd-demo .
    
        - name: Push image
          run: docker push raupechr/cicd-demo:latest
